# Generated by Django 3.1.3 on 2020-11-24 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField(default='Lorem ipsum dolor sit amet consectetur adipisicing elit. Error, dignissimos recusandae enim deserunt repellendus voluptatibus molestiae accusantium vitae velit! Labore fugiat cumque voluptas voluptatum numquam! Quisquam inventore animi dolorem adipisci!')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='When the post was published')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
